name: This is test workflow
on: 
    push:
        branches:
            - feature/a*
    pull_request:
        types:
            - opened
        branches:
            - main
jobs:
    Integration_Job:
              runs-on: ubuntu-22.04
              steps:
                - name: Login to the git repo
                  run: echo "Logged in"
                - name: Run Multiline commands
                  run: |
                      echo "Hello, this is line1"
                      echo "Hello, this is line2"
    Deployment_Job:
               runs-on: ubuntu-latest
               needs: Integration_Job
               steps:
                   - name: This is to deploy the application 
                     run: echo "Deploying the Application"
                   - name: This is to work on multi line
                     run: |
                         echo " This is line 1 from Deployment Job"
                         echo " This is line 2 from Deployment Job"
    Test_Vars_Secrets:
        runs-on: ubuntu-latest
        needs: Deployment_Job
        steps:
            - name: This is to test Variable
              run: echo "This is from Repository variables my address is ${{vars.ADDRESS}}
            - name: This is to test the secrets
              run: echo "The secret is ${{secrets.MY_TEST_SECRET}}
