name: This workflow is for Project Integration work purpose
on: [push,workflow_dispatch]
jobs:
    Integration_Job:
              runs-on: ubuntu-22.04
              steps:
                - name: Login to the git repo
                  run: echo "Logged in"
                - name: Run Multiline commands
                  run: |
                  echo "Hello, this is line1"
                  echo "Hello, this is line2"
