name: Workflow to get context variables
on: workflow_dispatch
jobs:
  context_vars_Info:
    runs-on: ubuntu-latest
    steps:
      - name: Get context variables Info
        run: echo "This workflow is executed by ${{ github.actor }} "
      - name: To get repo details
        run: echo "The repo is ${{github.repository}}
      - name: To list all the context variables in github
        run: echo "{{tojson(github)}}"
      - name: To print env variables
        run: echo "$GITHUB_SHA"
