name: This workflow is for IF condition checks
on: 
  pull_request:
    branches:
      - main
      - feature/a_test
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - feature/b_test
jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event.name == 'pull_request'
    steps:
      - name: This is just to Build the image
        run: echo "Image Building..."
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: This is just to deploy the image
        run: echo "Deploying the image"
        
