name: Workflow for IF conditions for dev project
on:
  pull_request:
    branches:
      - master
      - master1
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
jobs:
  Build_Job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
    steps:
      - name: Build the Image
        run: echo "This is Build Job"
  Deploy_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'master'
    steps:
      - name: Deploy the Image
        run: echo "This is Deploy Job"
        
