name: This is to test environment and send the notifications
on:
  push:
    branches:
      - test
      - dev
      - prod
jobs:
  test_env_job:
    if: startswith(github.ref_name,'test') && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: This is for test envitonment
        run: echo " This is running from test environment Job"
  dev_env_job:
    if: github.ref_name == 'dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: This is for dev environment
        run: |
          echo "This is running from Dev environment Job"
          exit 1
  prod_env_job:
    if: github.ref_name == 'prod' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: This is for Prod environment
        run:  echo "'This is from Prod environment"
  succc_notify:
    needs: [ test_env_job,dev_env_job,prod_env_job ]
    if: always() && !failure()
    runs-on: ubuntu-latest
    steps:
      - name: This is to send succesful notification
        run: echo "This is successful"
  failure_notify:
    needs:  [ test_env_job,dev_env_job,prod_env_job ]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: This is to send Failure Notification
        run: echo " This is Failed"
