name: Salaries for Family members
on:
  workflow_dispatch:
    inputs:
      Name_Info:
        description: Enter the name of the family member
        required: true
        type: choice
        options:
          - Karthik
          - Praneeth
          - Rohithas
          - Dharshik
      Salaries_Info:
        description: Enter the salaries of the family member
        required: true
        type: choice
        options:
          - 50L
          - 1CR
          - 2CR
          - 5CR
      Age_Info:
        description: Age of the family member
        required: false
        type: choice
        options:
          - 4Y
          - 16Y
          - 18Y
          - 37Y
jobs:
  Member_Info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Entire info of the family member
        run: echo "The Family member ${{inputs.Name_Info}} is of Age ${{inputs.Age_Info}} is earning ${{inputs.Salaries_Info}}"
    
