name: Workflow for IF condition task
on: 
  push:
    branches:
      - main
      - feature/a_test
  pull_request:
    branches:
      - main
      - feature/a_test
    types:
      - opened
      - synchronize
jobs:
  Build_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Build Job
        if: github.event_name == 'pull_request'
        run: echo "This is running from Build Job"
  Deploy_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy job
        run: echo "This is from Deploy Job"
        
