name: Checking IF condition
on: workflow_dispatch
jobs:
  check_ifcondition:
    runs-on: ubuntu-latest
    steps: 
      - name: testing scenarios use IF condition
        if: github.ref_name == 'main' || 'feature/a_test'
        run: echo "This is tested using IF condition"
      - name: Testing without condition
        run: echo "This is without testing"
