name: This workflow is to test the outputs
on: workflow_dispatch
jobs:
  os_info:
    outputs:
      res: ${{steps.OSID.outputs.OS}}
    runs-on: ubuntu-latest
    steps:
      - name: Get the OS info
        id: OSID
        run: echo "OS=Redhat" >> $GITHUB_OUTPUT
  Get_info:
    needs: os_info
    runs-on: ubuntu-latest
    steps:
      - name: To get the OS info from previous Job
        run: echo "The installed OS across environments is ${{needs.os_info.outputs.res}}"
